2024-07-28 09:42:15.515 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 09:42:30.383 | INFO     | routers.default:welcome:36 - User runit_mak start registration
2024-07-28 09:42:52.814 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 09:43:33.634 | INFO     | routers.registration:new_registration:29 - User runit_mak start new registration
2024-07-28 09:50:46.002 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 09:51:15.020 | INFO     | routers.registration:process_assistance:134 - User runit_mak registered
2024-07-28 09:51:41.793 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 09:51:59.221 | INFO     | routers.registration:process_assistance:124 - Delete old runit_mak info
2024-07-28 09:51:59.235 | INFO     | routers.registration:process_assistance:134 - User runit_mak registered
2024-07-28 09:53:52.605 | INFO     | routers.registration:new_registration:29 - User runit_mak start new registration
2024-07-28 09:54:08.259 | INFO     | routers.registration:process_assistance:124 - Delete old runit_mak info
2024-07-28 09:54:08.261 | INFO     | routers.registration:process_assistance:134 - User runit_mak registered
2024-07-28 09:54:20.736 | INFO     | routers.select_meet:process_hour_schedule:82 - User runit_mak schedule meeting: 29.07, 12:00
2024-07-28 09:56:01.116 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 09:56:11.247 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 09:56:22.030 | INFO     | routers.registration:process_assistance:125 - Delete old runit_mak info
2024-07-28 09:56:22.050 | INFO     | routers.registration:process_assistance:135 - User runit_mak registered
2024-07-28 09:58:11.323 | INFO     | routers.select_meet:process_hour_schedule:82 - User runit_mak schedule meeting: 01.08, 16:00
2024-07-28 09:59:07.621 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 09:59:28.711 | INFO     | routers.registration:process_assistance:125 - Delete old runit_mak info
2024-07-28 09:59:28.714 | INFO     | routers.registration:process_assistance:135 - User runit_mak registered
2024-07-28 10:09:57.821 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:11:44.730 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:12:38.654 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:14:03.428 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:14:14.681 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 10:14:25.699 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 10:14:29.572 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 10:15:28.654 | INFO     | routers.registration:new_registration:30 - User runit_mak start new registration
2024-07-28 10:26:50.103 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:27:03.819 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:27:08.582 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:27:55.693 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:27:56.812 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:28:15.807 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:28:35.375 | INFO     | routers.registration:process_assistance:131 - Delete old runit_mak info
2024-07-28 10:28:35.379 | INFO     | routers.registration:process_assistance:141 - User runit_mak registered
2024-07-28 10:28:46.847 | INFO     | routers.select_meet:process_hour_schedule:88 - User runit_mak schedule meeting: 30.07, 12:00
2024-07-28 10:28:52.751 | ERROR    | routers.get_gift:process_gift:29 - 'NoneType' object has no attribute 'from_user'
Traceback (most recent call last):
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/routers/get_gift.py", line 21, in process_gift
    await bot.get_chat_member(CHANNEL_NAME, call.from_user.id)
AttributeError: 'NoneType' object has no attribute 'from_user'
2024-07-28 10:28:59.485 | ERROR    | routers.get_gift:process_gift:29 - 'NoneType' object has no attribute 'from_user'
Traceback (most recent call last):
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/routers/get_gift.py", line 21, in process_gift
    await bot.get_chat_member(CHANNEL_NAME, call.from_user.id)
AttributeError: 'NoneType' object has no attribute 'from_user'
2024-07-28 10:30:50.507 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:31:28.849 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:31:39.415 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:32:33.425 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:32:36.393 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:32:42.859 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:33:15.062 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:33:27.472 | ERROR    | routers.get_gift:process_gift:30 - Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/routers/get_gift.py", line 22, in process_gift
    await bot.get_chat_member(CHANNEL_NAME, exec_user.from_user.id)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/bot.py", line 1700, in get_chat_member
    return await self(call, request_timeout=request_timeout)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
2024-07-28 10:33:42.332 | INFO     | routers.registration:new_registration:36 - User runit_mak start new registration
2024-07-28 10:35:43.992 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:35:46.424 | INFO     | routers.registration:new_registration:38 - User runit_mak start new registration
2024-07-28 10:35:50.055 | INFO     | routers.registration:new_registration:38 - User runit_mak start new registration
2024-07-28 10:35:52.294 | INFO     | routers.registration:new_registration:38 - User runit_mak start new registration
2024-07-28 10:36:13.621 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 10:36:14.369 | INFO     | routers.registration:new_registration:38 - User runit_mak start new registration
2024-07-28 10:36:57.589 | INFO     | __main__:main:19 - Bot has been started
2024-07-28 15:49:22.444 | INFO     | __main__:main:21 - Bot has been started
2024-07-28 15:50:43.506 | INFO     | routers.registration:new_registration:29 - User runit_mak start new registration
2024-07-28 15:51:37.474 | INFO     | routers.registration:process_assistance:124 - Delete old runit_mak info
2024-07-28 15:51:37.494 | INFO     | routers.registration:process_assistance:134 - User runit_mak registered
2024-07-28 15:54:31.055 | INFO     | routers.select_meet:process_hour_schedule:87 - User runit_mak schedule meeting: 01.08, 12:00
2024-07-28 15:54:37.237 | ERROR    | routers.get_gift:process_gift:31 - Telegram server says - Bad Request: chat not found
Traceback (most recent call last):
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/routers/get_gift.py", line 23, in process_gift
    await bot.get_chat_member(CHANNEL_NAME, call.from_user.id)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/bot.py", line 1700, in get_chat_member
    return await self(call, request_timeout=request_timeout)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
  File "/Users/maxkolt/Desktop/Work/Freelance/InvestClubBot/lib/python3.11/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: chat not found
